retreive_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    The list of 5 websites with the most relevant information about {topic}
  agent: retreive_news

website_scrape_task:
  description: >
   Scrape the website for the latest news and information
  expected_output: >
    Fully scraped websites with all the important information from the website
  agent: website_scraper

news_write_task:
  description: >
   SUmmarize the new information from the websites into a fully fledge news article in markdown format
  expected_output: >
    A fully fledged news articlet with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: news_writer

file_write_task:
  description: >
    Write the news article to the file
  expected_output: >
    A fully fledged news article with all the information from previous task into a file named news/{date}_news_article.md
    Formatted as markdown without '```'
  agent: file_writer


